exports.run = async function(context) {
    console.log('[step:write] write running...');
    // Example: return a file_ops instruction
    const ops = [
        { op: 'create', path: 'generated/v4_stub.txt', content: 'Generated by V4 write step', role: 'v4' }
    ];
    return { status: 'done', output: { note: 'write done' }, ops };
};
